#!/usr/bin/env bash
# Generate supabase/seed.dummy.sql from the current live database.
#
# Produces a data-only dump that preserves everything visible on the
# public site — event titles, logos, photos, usernames, org names,
# descriptions, locations, dates, prices, reviews, sponsors — but
# scrubs every real email in place with <username>@example.test and
# NULLs / dummies the payment and secret-code surfaces.
#
# Requires a Postgres connection URL with SELECT on public + auth,
# supplied via $DATABASE_URL or as the sole positional argument.
#
# Usage:
#   DATABASE_URL='postgres://…' bash scripts/generate-seed-dummy.sh
#   bash scripts/generate-seed-dummy.sh 'postgres://…'
#
# The output is deterministic (email scrubbing is derived from the
# user's UUID, not random) so the same input DB yields the same seed.
# Ends with a verification query that MUST return zero rows before the
# file is safe to commit.

set -euo pipefail

DB_URL="${1:-${DATABASE_URL:-}}"
if [[ -z "$DB_URL" ]]; then
  echo "Error: pass a Postgres URL or set \$DATABASE_URL" >&2
  exit 1
fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/supabase/seed.dummy.sql"
TMP_STAGING_SCHEMA="tg_seed_staging_$(date -u +%Y%m%d%H%M%S)"

echo "→ Materializing scrubbed staging schema: $TMP_STAGING_SCHEMA"

# Everything in one transaction: create staging schema, copy tables,
# scrub, dump, drop. If any step fails, ROLLBACK leaves the source DB
# untouched.
psql "$DB_URL" <<PSQL
begin;

create schema $TMP_STAGING_SCHEMA;

-- Copy tables whose content should be preserved (structure + rows).
-- Add columns to overwrite in the follow-up UPDATEs.
create table $TMP_STAGING_SCHEMA.profiles          as select * from public.profiles;
create table $TMP_STAGING_SCHEMA.events            as select * from public.events;
create table $TMP_STAGING_SCHEMA.reviews           as select * from public.reviews;
create table $TMP_STAGING_SCHEMA.user_teams        as select * from public.user_teams;
create table $TMP_STAGING_SCHEMA.event_ages        as select * from public.event_ages;
create table $TMP_STAGING_SCHEMA.event_genders     as select * from public.event_genders;
create table $TMP_STAGING_SCHEMA.event_fields      as select * from public.event_fields;
create table $TMP_STAGING_SCHEMA.event_features    as select * from public.event_features;
create table $TMP_STAGING_SCHEMA.event_competition_levels as select * from public.event_competition_levels;
create table $TMP_STAGING_SCHEMA.event_age_groups  as select * from public.event_age_groups;
create table $TMP_STAGING_SCHEMA.event_profiles    as select * from public.event_profiles;
create table $TMP_STAGING_SCHEMA.sponsors          as select * from public.sponsors;
create table $TMP_STAGING_SCHEMA.testimonials      as select * from public.testimonials;

-- Scrub emails on profiles. Derive from the row's own id so the same
-- input DB always yields the same seed (no Math.random surprises).
update $TMP_STAGING_SCHEMA.profiles
   set contact_email = 'user_' || substr(id::text, 1, 8) || '@example.test';

-- Scrub emails on reviews (denormalized reviewer email, PII).
update $TMP_STAGING_SCHEMA.reviews
   set user_email      = case when author_id is not null
                              then 'user_' || substr(author_id::text, 1, 8) || '@example.test'
                              else 'reviewer_' || substr(id::text, 1, 8) || '@example.test'
                         end,
       -- username_search is a lowercase search key; recompute so it
       -- still matches whatever username survived the copy.
       username_search = lower(coalesce(username, ''));

-- NULL out phone numbers on any table that stores them.
-- (contact_requests is dumped empty — see below — so no phone update
-- there; cards is also dumped empty.)
update $TMP_STAGING_SCHEMA.profiles set stripe_id = null;

-- Empty tables that must contain zero real rows in the dummy seed.
-- Kept as empty CREATE TABLE ... AS ... WHERE FALSE to preserve the
-- shape without any data.
create table $TMP_STAGING_SCHEMA.cards            as select * from public.cards            where false;
create table $TMP_STAGING_SCHEMA.promo_codes      as select * from public.promo_codes      where false;
create table $TMP_STAGING_SCHEMA.contact_requests as select * from public.contact_requests where false;
create table $TMP_STAGING_SCHEMA.submitted_csvs   as select * from public.submitted_csvs   where false;
create table $TMP_STAGING_SCHEMA.transactions     as select * from public.transactions     where false;

commit;
PSQL

echo "→ Dumping scrubbed staging schema to $OUT"

{
  cat <<HDR
-- =====================================================================
-- Tournament Guru — dummy seed derived from the live database.
--
-- AUTO-GENERATED by scripts/generate-seed-dummy.sh. Do not hand-edit.
--
-- Preserves everything the public site displays — event titles, logos,
-- photos, usernames, org names, descriptions, locations, dates, prices,
-- reviews, sponsors — but scrubs:
--   • every real email → user_<8-char-uuid-prefix>@example.test
--   • profiles.stripe_id → NULL
--   • cards, promo_codes, contact_requests, submitted_csvs, transactions
--     dumped as empty tables (structure only)
--
-- Load into a fresh schema-only DB (after running supabase/schema.sql)
-- with psql -f seed.dummy.sql. The verification query at the end MUST
-- return zero rows; if it doesn't, DO NOT USE THIS FILE.
-- =====================================================================

HDR

  # pg_dump --data-only preserves INSERT ordering by table dependency.
  # --column-inserts makes each row an explicit INSERT so re-runs on a
  # partial DB behave predictably.
  pg_dump "$DB_URL" \
    --schema="$TMP_STAGING_SCHEMA" \
    --data-only \
    --column-inserts \
    --no-owner \
    --no-privileges \
    --format=plain \
  | sed "s/${TMP_STAGING_SCHEMA}\\./public./g"

  cat <<'FTR'

-- ── Verification ─────────────────────────────────────────────────────
-- These two queries must return zero rows. If either returns any rows,
-- the scrub let a real email through; DO NOT commit this file.
select 'profiles leaked email' as failure, id, contact_email
  from public.profiles
 where contact_email is not null
   and contact_email !~ '@example\.test$';

select 'reviews leaked email' as failure, id, user_email
  from public.reviews
 where user_email is not null
   and user_email !~ '@example\.test$';
FTR
} > "$OUT"

# Drop the staging schema.
psql "$DB_URL" -c "drop schema $TMP_STAGING_SCHEMA cascade;"

echo "→ Wrote $OUT"
echo "→ Now run: psql \"\$DATABASE_URL_DUMMY\" -f $OUT — the last two SELECTs must return zero rows."
